### PR TITLE
Cloudwatch Updates

### PR DESCRIPTION
**Pull request by nicgrayson**
I pulled this down to use the cloudwatch features. I found a couple of things:
1. There are a few places where cloud_watch is used instead of cloudwatch. It's a little confusing
2. The key dimension should be dimensions
3. When you change the name of an alarm it wouldn't delete the old one

This PR addresses all three issues.

### CODE REVIEW

**Comment by xaptronic** [comment]
Nice, I'll pull this in.

Thanks!

**Comment by xaptronic** [comment]
Looking at the documentation for a number of the other aws provider resources, such as https://terraform.io/docs/providers/aws/r/elb.html, they use the singular "listener" even though there can be multiple. I attempted to follow the same convention with dimension because each dimension is listed in a separate block, e.g.;

```
dimension {
    name = "AutoScaleGroupName"
    value = "${aws_autoscaling_group.bar.name}"
}
dimension {
    name = "AutoScaleGroupName"
    value = "${aws_autoscaling_group.foo.name}"
}
```

Any thoughts about whether dimension should still move to be pluralized or kept singular?

**Comment by nicgrayson** [comment]
@xaptronic I was really confused when I setup the resource that it was singular. I think it's because it's a map with more than one value in this case not separate in the case of a listener. I called it like this:
dimensions = {
  AutoScaleGroupName = "${aws_autoscaling_group.bar.name}"
  AutoScaleGroupName = "${aws_autoscaling_group.foo.name}"
}

If it's meant to be called like your last comment I can see why singular makes sense. Do they both work?

**Comment by xaptronic** [comment]
@nicgrayson I see - I think given these are name / value only the way you wrote yours is more concise. I think some of the other examples have additional values (like autoscaling_group has propagate_at_launch) and so requires further expansion.

I'll pull your changes and make note to write the docs / examples how you wrote it instead.

Thanks!

**Pull request merged**
